### ISSUE TITLE
Make debug easier

### ISSUE THREAD

**Issue by Maxou44** [UnicornTranscoder/UnicornTranscoder#47]
It could be nice if a FFMPEG_DEBUG env value allows us to store/hide the ffmpeg logs in UnicornTranscoder logs by changing the log level parameter

**Comment by raphaelfumfahr** [comment]
Hey, how about the transcoder writes the debug log to a file like: debug-YY-MM-DD.log so the whole log would read much easier. I think that would be a good feature.

**Comment by Maxou44** [comment]
What kind of debug do you want ?

**Comment by raphaelfumfahr** [comment]
What I'd like to have in my log? At the moment I have DEBUG=* because streams stop after X minutes, or the transcode hangs. Not for all only for a few users. And I'm currently trying to filter out the error, but I get so much data when felt 5-10 users look at it that it just doesn't remain readable.

**Comment by drouarb** [comment]
If you want only UnicornTranscoder logs you can set to DEBUG=UnicornTranscoder*

**Comment by raphaelfumfahr** [comment]
Okay I'll test, but I still think that you should save the debug log to a file, so it's easier to handle then.
