### ISSUE TITLE
Extracting versions

### ISSUE THREAD

**Issue by davidjameshowell** [UnicornTranscoder/UnicornTranscoder#80]
Could you provide some instructions on where exactly we can extract the Plex versions (EAE, codecs mainly) that are relevant to the config? I am a bit confused on where these values are derived from.

**Comment by drouarb** [comment]
The versions are hardcoded in the binary, the way to extract it is documented in https://github.com/UnicornTranscoder/UnicornTranscoder#plex-version-configuration
Theses commands should be run next to the `Plex Media Server` binary on Linux.
It's pretty tricky, and since the 1.18 the EAE version can't be fully extracted.

**Comment by davidjameshowell** [comment]
Thank you! I didn't put two and two together to see the binary in the strings command.
