### ISSUE TITLE
404 error on GeoIP based routing

### ISSUE THREAD

**Issue by Phet0902** [UnicornTranscoder/UnicornTranscoder#88]
Hi there,
I've set up my environment as described in your manual. LB/FFmpeg on one server, one transcoder in one location and second transcoder in another location. Have setup the GeoIP routing as well, and it is working as described. I can see, based on the location of my client, that the correct transcoder is selected by the LB. 

However, if LB select the transcoder due-to geoip routing close to it (LB and Transcoder are in the same DC, Client in the same regional IP range) it works and the stream starts:

transcoder picks up the request from LB:

![geosite_a_Transcoder](https://user-images.githubusercontent.com/37608624/79323181-0f4fb700-7f38-11ea-849b-da30fed2a09a.JPG)

Output FFMpge:

![geosite_a_ffmpg](https://user-images.githubusercontent.com/37608624/79323257-25f60e00-7f38-11ea-9421-83eb25a31704.JPG)

In case the geoip routing select the other transcoder the stream hangs on 404 siting the files are not available for streaming (even if those files exist on the transcoder server)

![geosite_b_Transcoder](https://user-images.githubusercontent.com/37608624/79323505-7bcab600-7f38-11ea-8c1f-9942a8efcd46.JPG)

Output FFMpge:

![geosite_b_ffmpg](https://user-images.githubusercontent.com/37608624/79323537-89803b80-7f38-11ea-83d7-f82de706461b.JPG)

So from my testing and observations, any transcoder close to the LB are working fine. Any transcoder distant from the LB prduces 404 only.

**Comment by Maxou44** [comment]
Can we see your transcoder configuration ?
Your file are mounted on each transcoders ?

**Comment by Phet0902** [comment]
You, here we go...

SERVER_PORT=3000
SERVER_LISTEN='172.0.0.1'
TRANSCODER_DECAY_TIME=120
LOADBALANCER_ADDRESS='https://x.x.x.x.net'
PING_FREQUENCY=3
INSTANCE_ADDRESS='https://y.y.y.y.net'

MAXMIND_KEY='abc123456'

PLEX_ARCH='amd64'
PLEX_BUILD='1.18.9.2578-513b381af'
CODECS_BUILD='99c90e0-3084'
EAE_VERSION='eae-69c1de6-42'
PLEX_RESOURCES='plexmediaserver/'
TEMP_FOLDER='cache/'
CODECS_FOLDER='codecs/'
PLEX_TRANSCODER='Plex Transcoder'
TRANSCODER_DEBUG=true

MAX_SESSIONS=8
MAX_DOWNLOADS=8
MAX_TRANSCODE=8

Yes, each transcoder server is mounted to the same filestore

Yes, installed the newest version, v2.5

The response from the 404 is 'Callback -2'

**Comment by Maxou44** [comment]
If you disable the geoip, is it working ?

**Comment by Maxou44** [comment]
The issue is here:
SERVER_LISTEN='172.0.0.1' 

The ffmpeg can't send the message to the Transcoder, set it to '0.0.0.0', it will work better 😉

**Comment by Phet0902** [comment]
I changed the env variable, rebooted but the 404 is still there...

Output ffmpge:

![geosite_b_ffmpg_01](https://user-images.githubusercontent.com/37608624/79427454-ea6a4b00-7fee-11ea-8c48-5cbd308139d2.JPG)

Response from 404 is still "Callback-2"

**Comment by Phet0902** [comment]
I disabled geoip as well, infact the transcoder in question is currently the only one active. And yes after the update I did a npm run install

**Comment by Maxou44** [comment]
SESSION_TIMEOUT mean there is an issue on your load balancer configuration like :
- Plex Transcoder wasn't replaced
- Plex relay wasn't removed
-Plex database isn't correctly localized

**Comment by Phet0902** [comment]
I will run trough all your point and give you a feedback... Strange enought, the transcoder in the same dc (also same configuration) has no problems

**Comment by Maxou44** [comment]
Can you check `https://<lbaddress>/api/stats/` and see if the transcoder is correctly registered ?

**Comment by Phet0902** [comment]
#1: Transcoder on LB Server has been replaced with the Unicorn FFMP
#2: Plex Relay removed
#3: DB correctly localized
#4: 32400 on LB Server closed

![reg](https://user-images.githubusercontent.com/37608624/79429423-af1d4b80-7ff1-11ea-8a5d-68d61f55a60b.jpg)

**Comment by Maxou44** [comment]
can you disable geoip stuff and see if everything works ?

**Comment by Phet0902** [comment]
is disabled on all transcoder. test one server transcoder in same DC, works. Server with server transcoder different location than LB Server, doens't work (404)

**Comment by Maxou44** [comment]
did you see this transcoder (nother dc) in api/stats ?

**Comment by Phet0902** [comment]
yes I can switch on both without geoip and i can see them both in https://<lbaddress>/api/stats/

**Comment by Maxou44** [comment]
Geoip is only to solve peering issues, not to find the best transcoder based on location, you can't see geoip "addresses" in the /api/stats, right?

**Comment by Phet0902** [comment]
No I can't dee it just route, but based on my client IP the routing points to the right transcoder

**Comment by Maxou44** [comment]
I think the feature isn't appropriate to your case, the goal is only to solve peering issues, not dispatch transcodes between different DC based on IP

**Comment by Phet0902** [comment]
Thats such a pitty, coz this would solve 90% of my Plex setup in the "cloude"

**Comment by Maxou44** [comment]
Why do you need geoip location ? Setup 2 transcoders will solve exactly the same issue ;)

**Comment by Phet0902** [comment]
That is due to my "lifestyle" working in Europe and States, living in Asia. the setup I have is as following: LB/FFMPG DC Germany, 1. Transcoder same DC, second Transcoder DC Amsterdam and another (3. Transcoder) Close to home in DC Singapore.

**Comment by Phet0902** [comment]
Transcoding from DC Germany to Asia has constant buffer issues in Plex

**Comment by Maxou44** [comment]
Did you try Cloudflare behind your transcoder ?

**Comment by Phet0902** [comment]
Yes I was afraid you would say this, means two Plex server and the maintenance (Play State, etc.) via trakt

**Comment by Maxou44** [comment]
Sorry for this bad news 😅

**Comment by Maxou44** [comment]
The other solution is to copy your files in an Asia DC

**Comment by Phet0902** [comment]
YEs I had done this in the past. Running a db sync/rplication on a schedule. But your solution would have been the solution fro that.One central Entry (LB) several locations for streaming (Trans)...

**Comment by Maxou44** [comment]
If it's a peering issue, it will be worst to set a transcoder in Asia, because the transcoder will download all the media file from another country to compress it and the size of the media file is higher than transcoded chunks.

**Comment by Maxou44** [comment]
After a talk with @drouarb, the 404 Timeout is not normal, there is an issue in your settings

**Comment by drouarb** [comment]
les me clarify some points, what happens when you transcode:
1. Your client requests plex
2. The `UnicornLoadBalancer` catch the query and redirect it to the transcoder
3. The `UnicornTranscoder` will fire a query to `Plex Media Server` to start the transcode
4. Plex start `Plex Transcoder` that has been replaced by `UnicornFFMPEG`
5. `UnicornFFPEG` send transcoding arguments to `UnicornLoadBalancer`
6. `UnicornTranscoder` pull arguments from `UnicornLoadBalancer` and start a transcoding session
7. The `Plex Transcoder` on your transcoder will ping `Plex Media Server` with some metadata to allow Plex to generate the mpd manifest
8. `UnicornTranscoder` send the manifest to your client, the transcode session is started


If you have a Session Timeout, it happends in the step 6 when the transcoder requests arguments from `UnicornLoadBalancer`, it means that UnicornLoadBalancer didn't received the transcoding arguments.
The weird parts is the moment UnicornLoadBalancer don't get the arguments, it means:
- The start.mpd request didn't successfully reached Plex Media Server
- Plex didn't started the sessions
- UnicornFFMPEG didn't properly sent arguments to UnicornLoadBalancer

I would advise you to run the`UnicornLoadBalancer` with `DEBUG=*` environement variable and check that you have the 2 requests: `start.mpd` (Plex web client request) & `/api/ffmpeg/` (UnicornFFMPEG request)

For the GeoIP part:
The GeoIP has been built specially because we needed good performances on asia.
Actually, the peering between Europe/US and Asia is very bad, but some operator have some good performances on this region. Everything depends on the ISP you will take. Our ISP has a pretty bad peering to Asia, but Cloudflare has a partnership with Baidu and have a good peering over Asia.
We didn't want to send all our transcode session through Cloudflare, because with Cloudflare connections are limited to ~6Mo/s, so we decided that all our request from specific countries will go through Cloudflare meanwhile other connections will be direct.

So how to setup it:
Setup a normal transcoder, then setup a Cloudflare on a different domain that will fall on the transcoder.
Then, in the routing section:
```js
routing: {
  'CN': 'https://cloudflare.myplex.com'
}
```
This will route every Chinese IP to this domaine, forcing the user to go through Cloudflare. All other user will still use the `INSTANCE_ADDRESS` domain.

Finally:
I do not recommend setup a transcoder in an other region than your storage:
The transcoder will jump in the file and recompress it, this is a heavy operation for the network, so, it is better to setup your transcoder in a region close to your storage.

**Comment by Phet0902** [comment]
@drouarb thank you very much for the time to write this explanation down. I will for sure tryh the way with cloudflare to test and give some feedback. The file location is provided by Google Shared TeamDrive, so I surposet that the servers are located in the states.

for the setup of transcoders, as I mentioned previously, Transcoder located close to the LB (MUC & AMS) are working just fine. The one in SIN ist the one making problems. Debugging that transcoder I can see the reqyest is received and FFMpeg is starting the transconding job, however falls short of continuing after the first chuck. That is when it start spitting out 404.

**Comment by drouarb** [comment]
FFMPEG ping a on a callback URL once a chunk is done. If you get a `404 Callback -2`, this means that FFMPEG didn't sent the chunk callback in time. I think the FFMPEG can't work fast enough due to the poor network peering.
There is not much we can do in the software to fix this issue. I advise you to either setup your transcoder closer to your storage or replicate your storage close to your transcoder.

**Comment by Phet0902** [comment]
Thanks for your efforts :)
